### ISSUE TITLE
Converter error no image reader for format

### ISSUE THREAD

**Issue by omnislash772** [ChenThread/ctif#4]
when running the java converter with png or jpg files i get the following, it just states it cant open tif images

`ImageMagick found; using ImageMagick for resizing.
org.im4java.core.CommandException: java.lang.IllegalStateException: no ImageReader for given format
        at org.im4java.core.ImageCommand.run(ImageCommand.java:219)
        at pl.asie.ctif.Utils.resize(Utils.java:81)
        at pl.asie.ctif.Main.main(Main.java:270)
Caused by: java.lang.IllegalStateException: no ImageReader for given format
        at org.im4java.core.Stream2BufferedImage.consumeOutput(Stream2BufferedImage.java:82)
        at org.im4java.process.ProcessStarter.processOutput(ProcessStarter.java:276)
        at org.im4java.process.ProcessStarter.access$200(ProcessStarter.java:54)
        at org.im4java.process.ProcessStarter$2.call(ProcessStarter.java:433)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Generating palette...
Exception in thread "main" java.lang.NullPointerException
        at pl.asie.ctif.Utils.getRGB(Utils.java:119)
        at pl.asie.ctif.PaletteGenerator.<init>(PaletteGenerator.java:46)
        at pl.asie.ctif.Main.main(Main.java:275)`

and when running a tif image
`Could not load image: test.tif`

**Comment by Cruor** [comment]
I fixed this problem by adding Image Magicks path in `IM4JAVA_TOOLPATH` Env variable. Sadly it runs faster on a linux box :/

**Comment by sigmasoldi3r** [comment]
+1 Got the same problem, running under `Windows 10` with **java 8** :/

Edit: Just tested that solution, it should be pointed out in the documentation
