### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "image" is null

### ISSUE THREAD

**Issue by Wurst720** [ChenThread/ctif#9]

**Comment by Wurst720** [comment]
ImageMagick found; using ImageMagick for resizing.
org.im4java.core.CommandException: java.lang.IllegalStateException: no ImageReader for given format
        at org.im4java.core.ImageCommand.run(ImageCommand.java:219)
        at pl.asie.ctif.Utils.resize(Utils.java:81)
        at pl.asie.ctif.Main.main(Main.java:270)
Caused by: java.lang.IllegalStateException: no ImageReader for given format
        at org.im4java.core.Stream2BufferedImage.consumeOutput(Stream2BufferedImage.java:82)
        at org.im4java.process.ProcessStarter.processOutput(ProcessStarter.java:276)
        at org.im4java.process.ProcessStarter.access$200(ProcessStarter.java:54)
        at org.im4java.process.ProcessStarter$2.call(ProcessStarter.java:433)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:833)
Converting image...
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "image" is null
        at pl.asie.ctif.Converter.<init>(Converter.java:48)
        at pl.asie.ctif.Main.main(Main.java:314)
